const data = {
    products: [
        {
            name: 'A Wrinkle in Time',
            slug: 'a-wrinkle-in-time',
            category: 'Action & Adventure',
            image: '/images/p1.jpg',
            price: 44,
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            author: 'Madeleine L Engle',
            publicationDate: 2008,
            edition: 'Square Fish',
            pageNumber: 288,
            description: '"A Wrinkle in Time" is a classic science fantasy novel written by Madeleine L Engle. The story follows Meg Murry, her brother Charles Wallace, and their friend Calvin O Keefe as they embark on a cosmic journey to rescue Megs father. Guided by mysterious beings called Mrs. Whatsit, Mrs. Which, and Mrs. Who, the children traverse space and time, encountering strange worlds and confronting the forces of darkness. L Engle weaves themes of love, courage, and the battle between good and evil into a captivating narrative that transcends dimensions, making "A Wrinkle in Time" a timeless exploration of the human spirit and the mysteries of the universe.',
        },

        {
            name: 'Gullivers Travels',
            slug: 'gullivers-travels',
            category: 'Classics',
            image: '/images/p2.jpg',
            price: 37,
            countInStock: 10,
            rating: 4.2,
            numReviews: 10,
            author: 'Jonathan Swift',
            publicationDate: 2016,
            edition: 'Evergreens',
            pageNumber: 256,
            description: '"Gullivers Travels" is a satirical masterpiece penned by Jonathan Swift. The novel recounts the fantastic voyages of Lemuel Gulliver, a ships surgeon, to four extraordinary lands. From the miniature inhabitants of Lilliput to the towering Brobdingnagians, the flying island of Laputa, and the rational horses of Houyhnhnms, Gulliver encounters societies that mirror and critique various aspects of human nature and society. Swift employs humor, wit, and allegory to explore themes such as politics, power, and human folly. "Gullivers Travels" remains a timeless classic, celebrated for its sharp social commentary and imaginative storytelling.',
        },

        {
            name: 'Eleanor Oliphant is completely fine',
            slug: 'eleanor-oliphant-is-completely-fine',
            category: 'Contemporary Fiction',
            image: '/images/p3.jpg',
            price: 97.92,
            countInStock: 10,
            rating: 5,
            numReviews: 10,
            author: 'Gail Honeyman',
            publicationDate: 2018,
            edition: 'Penguin Books',
            pageNumber: 352,
            description: '"Eleanor Oliphant Is Completely Fine" by Gail Honeyman is a poignant and heartwarming novel that delves into the life of Eleanor Oliphant, a socially awkward and routine-driven woman. Eleanors carefully structured world takes an unexpected turn when she develops a crush on a musician and begins to navigate the complexities of social interactions. As the layers of Eleanors past are gradually revealed, the novel addresses themes of loneliness, trauma, and the transformative power of human connection. Gail Honeyman skillfully combines humor and empathy, crafting a compelling narrative that explores the resilience of the human spirit and the possibility of healing through friendship and self-discovery.',
        },

        {
            name: 'Hazards of Time Travel',
            slug: 'hazards-of0time-travel',
            category: 'Distopian Fiction',
            image: '/images/p4.jpg',
            price: 160.64,
            countInStock: 10,
            rating: 5,
            numReviews: 10,
            author: 'Joyce Carol Oates',
            publicationDate: 2018,
            edition: 'Harper Large Print',
            pageNumber: 432,
            description: '"Hazards of Time Travel" by Joyce Carol Oates is a thought-provoking science fiction novel that follows the story of Adriane Strohl, a rebellious teenager in a dystopian society. After expressing dissenting views in a school assignment, Adriane is sentenced to a mysterious form of punishment: time travel to the past. Transported to the 1950s, she must navigate a world of political unrest and conform to the norms of a different era. As Adriane grapples with the hazards of both her oppressive present and the complexities of the past, the novel explores themes of free will, authoritarianism, and the consequences of questioning societal norms. Oates weaves a compelling narrative that challenges perceptions of time, identity, and the impact of individual choices on the course of history.',
        },

    ],
};

export default data;